export const DATA = [
  {
    id: '1',
    img: '123',
    courseName: 'React Native Com Hooks Avançados Para iniciantes',
    author: 'Yuri Vinicius Ferreira Olivera',
    value: 'R$ 10,00',
    isFree: false,
  },
  {
    id: '2',
    img: '123',
    courseName: 'React Native',
    author: 'Yuri Vinicius',
    value: 'R$ 0',
    isFree: true,
  },
  {
    id: '3',
    img: '123',
    courseName: 'React Native',
    author: 'Yuri Vinicius',
    value: 'R$ 0',
    isFree: true,
  },
  {
    id: '4',
    img: '123',
    courseName: 'React Native',
    author: 'Yuri Vinicius',
    value: 'R$ 0',
    isFree: true,
  },
  {
    id: '5',
    img: '123',
    courseName: 'React Native',
    author: 'Yuri Vinicius',
    value: 'R$ 0',
    isFree: true,
  },
  {
    id: '6',
    img: '123',
    courseName: 'React Native',
    author: 'Yuri Vinicius',
    value: 'R$ 0',
    isFree: true,
  },
  {
    id: '7',
    img: '123',
    courseName: 'React Native',
    author: 'Yuri Vinicius',
    value: 'R$ 0',
    isFree: true,
  },
  {
    id: '8',
    img: '123',
    courseName: 'React Native',
    author: 'Yuri Vinicius',
    value: 'R$ 0',
    isFree: true,
  },
];
