const fs = require('fs-extra')

const createTheme = (dirDst, theme) => {
  console.log(`Write ${dirDst}/styles/colors.ts\n`)
  console.log(theme)
  const fileContent = `\
// NOTICE: This file is auto-generated by wl-engine.
export const colors = ${theme}

`
  fs.writeFileSync(`${dirDst}/styles/colors.ts`, fileContent)
  console.log('Wrote new colors 🌈\n')
}

module.exports = createTheme
